from django.urls import path
from .views import (
    QuestionListView,
    QuestionDetailView,
    QuestionCreateView,
    QuestionUpdateView,
    QuestionDeleteView,
    AnswerCreateView,
    AnswerUpdateView,
    AnswerDeleteView,
    VoteOnQuestionView,
    VoteOnAnswerView,
    AcceptAnswerView,
    UserRegistrationView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    ProfileView,
    ProfileUpdateView,
)

urlpatterns = [
    path('', QuestionListView.as_view(), name='question_list'),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='question_detail'),
    path('question/new/', QuestionCreateView.as_view(), name='question_create'),
    path('question/<int:pk>/edit/', QuestionUpdateView.as_view(), name='question_edit'),
    path('question/<int:pk>/delete/', QuestionDeleteView.as_view(), name='question_delete'),
    path('question/<int:pk>/answer/new/', AnswerCreateView.as_view(), name='answer_create'),
    path('answer/<int:pk>/edit/', AnswerUpdateView.as_view(), name='answer_edit'),
    path('answer/<int:pk>/delete/', AnswerDeleteView.as_view(), name='answer_delete'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('user/<str:username>/change-password/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('user/change-password/done/', CustomPasswordChangeDoneView.as_view(), name='password_change_success'),
    path('question/<int:pk>/vote/<str:vote_type>/', VoteOnQuestionView.as_view(), name='vote_on_question'),
    path('answer/<int:pk>/vote/<str:vote_type>/', VoteOnAnswerView.as_view(), name='vote_on_answer'),
    path('question/<int:question_pk>/answer/<int:answer_pk>/accept/', AcceptAnswerView.as_view(), name='accept_answer'),
    path('profile/', ProfileView.as_view(), name='my_profile_view'),
    path('profile/<str:username>/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile_view'),
]