# Generated by Django 5.1.3
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('sovf', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='sovf.answer'),
        ), 
        migrations.AlterField(
            model_name='answervote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')]),
        ),
    ]