# Generated by Django 5.1.3 on 2024-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovf', '0005_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(default='badges/default_badge.png', help_text='The image associated with this badge', upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('upvotes_received', 'Upvotes Received'), ('answers_accepted', 'Answers Accepted'), ('questions_posted', 'Questions Posted'), ('answers_posted', 'Answers Posted'), ('comments_posted', 'Comments Posted')], help_text='The type of milestone this badge tracks', max_length=50),
        ),
    ]
