# Generated by Django 5.1.3 on 2024-12-19 14:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sovf', '0007_alter_answer_content_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
